apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment-production
  namespace: production
spec:
  selector:
    matchLabels:
      app: microservice-deployment-production
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: microservice-production
    spec:
      containers:
      - name: microservice-production
        image: fallmann/cloud-native-microservice:1.0.0
        ports:
        - containerPort: 3000
          name: http-web-svc
        env:
        - name: PORT
          value: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment-staging
  namespace: staging
spec:
  selector:
    matchLabels:
      app: microservice-deployment-staging
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: microservice-staging
    spec:
      containers:
      - name: microservice-staging
        image: fallmann/cloud-native-microservice:latest
        ports:
        - containerPort: 5000
          name: http-web-svc
        env:
        - name: PORT
          value: "5000"
